services:
  ipsc-be-php:
    build: .
    container_name: ipsc-app-php
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - ${APP_PORT}:80
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./../src/:/var/www
      - ./php/dev/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - ipsc-db-php
    links:
      - ipsc-db-php
    networks:
      - ipsc-be-network

  ipsc-nginx:
    image: nginx:alpine
    container_name: ipsc-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../src/:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - adv-be-network

  ipsc-db-php:
    image: 'mariadb:latest'
    container_name: ipsc-db-php
    environment:
      - 'MARIADB_DATABASE=${DB_DATABASE}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MARIADB_USER=${DB_USER}'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - ipsc-be-network

  ipsc-pma:
    image: phpmyadmin/phpmyadmin
    container_name: ipsc-pma
    environment:
      - PMA_HOST=ipsc-db
      - UPLOAD_LIMIT=1G
    restart: always
    ports:
      - 8081:80
    networks:
      - ipsc-be-network

  ipsc-redis-php:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6380}:6379'
    volumes:
      - 'sail-redis8003:/data'
    networks:
      - ipsc-be-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    restart: unless-stopped

# Docker Networks
networks:
  ipsc-be-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local