services:
  ipsc-be-php-app:
    build:
      # use project root as build context so we can access all files
      context: ../
      args:
        - env=${APP_ENV}
      dockerfile: docker/Dockerfile
    image: laravel/php
    container_name: ipsc-be-php-app
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - ${APP_PORT}:80
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./../src/:/var/www
      - ./php/dev/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - ipsc-db-php
    links:
      - ipsc-db-php
    networks:
      - ipsc-be-network
      - app-network-ipsc-fe

  ipsc-nginx:
    image: nginx:alpine
    container_name: ipsc-nginx
    restart: ${DOCKER_RESTART_POLICY}
    tty: true
    ports:
      - ${NGINX_PORT}:80
      #- ${NGINX_SSL_PORT}:443
    volumes:
      - ./../src/:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - ipsc-be-network
      - app-network-ipsc-fe

  ipsc-db-php:
    image: 'mariadb:latest'
    container_name: ipsc-db-php
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - 'MARIADB_DATABASE=${DB_DATABASE}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MARIADB_USER=${DB_USERNAME}'
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ipscdbdata:/var/lib/mysql/
    networks:
      - ipsc-be-network
      - app-network-ipsc-fe

  ipsc-pma-php:
    image: phpmyadmin/phpmyadmin
    container_name: ipsc-pma-php
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - PMA_HOST=ipsc-db-php
      - UPLOAD_LIMIT=1G
    ports:
      - ${PMA_PORT}:80
    networks:
      - ipsc-be-network
      - app-network-ipsc-fe

  ipsc-redis-php:
    image: 'redis:alpine'
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - '${FORWARD_REDIS_PORT:-6380}:6379'
    volumes:
      - 'redisdata:/data'
    networks:
      - ipsc-be-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

# Docker Networks
networks:
  ipsc-be-network:
    driver: bridge
  app-network-ipsc-fe:
    external: true

# Volumes
volumes:
  ipscdbdata:
    driver: local
  redisdata:
    driver: local